// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHHnCu7SgxMG7hwS-iXzUqktdmkZ4OoFI',
    appId: '1:87487911593:android:ce4a4d999ab15f6dac7bb8',
    messagingSenderId: '87487911593',
    projectId: 'referhub-ec0d7',
    databaseURL: 'https://referhub-ec0d7.firebaseio.com',
    storageBucket: 'referhub-ec0d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5ULReu0fgC6wcYCx46NUe0H0yXoE2yY',
    appId: '1:87487911593:ios:1eb7daab75663273ac7bb8',
    messagingSenderId: '87487911593',
    projectId: 'referhub-ec0d7',
    databaseURL: 'https://referhub-ec0d7.firebaseio.com',
    storageBucket: 'referhub-ec0d7.appspot.com',
    iosClientId: '87487911593-7isu9prhce3u7kfvchvljhuj66uso13q.apps.googleusercontent.com',
    iosBundleId: 'com.itluobo.myReferHubApp',
  );
}
